# Generated by Django 5.2.10 on 2026-01-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_payment_shipping_staff_order_orderitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
